# Generated by Django 3.1.1 on 2020-09-06 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200904_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookisbn', models.TextField()),
                ('booktitle', models.TextField()),
                ('bookimg', models.TextField()),
                ('lover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listloves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
