# Generated by Django 3.1.1 on 2020-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookimg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='booktitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='bookyear',
            field=models.TextField(blank=True),
        ),
    ]
