# Generated by Django 3.1.1 on 2020-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200906_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookrating',
            field=models.TextField(blank=True),
        ),
    ]
